# nixpacks.toml
# Configuration for Railway deployment

[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip install -r requirements_railway.txt"]

[start]
cmd = "uvicorn api_service_supabase:app --host 0.0.0.0 --port ${PORT:-8000}"