# Railway Nixpacks configuration - Simplified without browser automation
# Browser automation will be handled separately in a future deployment

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "python -m pip install -r requirements-railway.txt"
]

[start]
cmd = "uvicorn api_minimal:app --host 0.0.0.0 --port $PORT"