[phases.setup]
nixPkgs = ["python311", "gcc", "postgresql", "chromium", "firefox"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements_railway.txt",
    "playwright install chromium",
    "playwright install-deps"
]

[start]
cmd = "uvicorn api_service_supabase:app --host 0.0.0.0 --port ${PORT:-8000}"