# Railway configuration with browser automation support
[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn api_minimal:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

# Environment configuration
[env]
PYTHON_VERSION = "3.11"
NODE_ENV = "production"