# Railway Deployment Optimization Workflow
# Place this in .github/workflows/railway-deploy.yml

name: Railway Deploy (Disabled)

on:
  # Manual only; Railway handles auto-deploy via GitHub integration
  workflow_dispatch:

jobs:
  no-op:
    runs-on: ubuntu-latest
    steps:
    - name: Explain
      run: |
        echo "Deployment via GitHub Actions is disabled."
        echo "Railway should be configured to auto-deploy on pushes via the Railway UI (Deploy from GitHub)."
        echo "This workflow is a manual placeholder and performs no deployment."
