[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7fafc"
textColor = "#2d3748"

[server]
port = 8501
headless = true
enableCORS = true
enableXsrfProtection = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false