# Streamlit secrets file (DO NOT COMMIT TO GIT)
# This file is for local development. In Streamlit Cloud, set these in the dashboard.

API_URL = "https://tax-extraction-system-production.up.railway.app"